name: Docker push

on:
  workflow_dispatch:
  schedule:
    - cron: '50 15 * * *'
  push:
    branches: 
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}
      - name: Docker Build
        run: docker-compose build 
      - name: Docker Push
        run: docker push tmvdl/kotlin -a
