name: Docker pull

on:
  workflow_dispatch:
  schedule:
    - cron: '50 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Docker pull
        run: docker pull tmvdl/kotlin -a
